### ISSUE TITLE
現在sqlmap更新了很多版之後有新的選項 能更新一下么？

### ISSUE THREAD

**Issue by 687766616e** [needle-wang/sqlmap-gtk#1]

**Comment by needle-wang** [comment]
哇, 有人反馈. 感谢!
好的。

**Comment by 687766616e** [comment]
nice~ hah😆😆

**Comment by 687766616e** [comment]
想問一下為什麼要用pip版而不是dev版呢？`1.3.4.34#dev`😅

**Comment by needle-wang** [comment]
我也clone了1.3.4.34#dev, 对比了下pip上的sqlmap -hh, 没发现区别, 就这么写啦.

**Comment by 687766616e** [comment]
ok...😅😅

**Comment by 687766616e** [comment]
你有辦法讓它可以在Windows系統上運行嗎？

**Comment by 687766616e** [comment]
https://chocolatey.org/packages?q=GTK <-- ==?   ^^''

**Comment by 687766616e** [comment]
還有...你可以弄一个web gui么？因為我想遠程推送任務 謝!😆
(利用`sqlmapapi.py`)

**Comment by needle-wang** [comment]
1. 确实可以在win上跑, 早前我试成功过.
    根据官方文档, 必须用msys2. 然后装一堆的gtk依赖, 界面不好看, 我还打算放弃win呢.
    我之前用wxWidgets重写过一次, 结果在win下运行后的布局惨不忍睹. wxWidgets实在太难用了.
    如果改成QT, 也许能跨平台, 目前没有研究QT的计划.
2. 现在基本所有功能都有在ui上了, 还差sqlmapapi.py没处理, 因为之前没这打算.
    近期, 如果有时间, 我研究下吧.

**Comment by needle-wang** [comment]
> 
> 
> 你有辦法讓它可以在Windows系統上運行嗎？

https://www.freebuf.com/sectool/7144.html

**Comment by 687766616e** [comment]
https://github.com/sqlmapproject/sqlmap/blob/master/lib/parse/cmdline.py

**Comment by 687766616e** [comment]
有些隱藏功能没写在usage页

**Comment by needle-wang** [comment]
> 有些隱藏功能没写在usage页

嗯~, 我看了下, 那些好像都是调试用的选项;
没有详细说明, 没什么实际用处吧?

**Comment by 687766616e** [comment]
有。。。比如这个 [ --base64](https://github.com/sqlmapproject/sqlmap/issues/1387#issuecomment-484060983)
没说明的话可以google一下

**Comment by 687766616e** [comment]
`--base64`: 
```
site:github.com inurl:github.com/sqlmapproject/sqlmap/issues "--base64"
```

**Comment by 687766616e** [comment]
还有。。。web gui....😅😅拜託了。。。(整个网络也没？。。。。。。

**Comment by 687766616e** [comment]
https://github.com/needle-wang/sqlmap-gtk/issues/1#issuecomment-489316557
沒在更新了呀....

**Comment by needle-wang** [comment]
> 还有。。。web gui....sweat_smilesweat_smile拜託了。。。(整个网络也没？。。。。。。

嗯~, 隐藏选项, 我看看吧, 有时间再加上几个.
web gui的功能早就已经写完了呀, 在 API区 标签页就是了

**Comment by 687766616e** [comment]
NICE~😃

**Comment by needle-wang** [comment]
> [#1 (comment)](https://github.com/needle-wang/sqlmap-gtk/issues/1#issuecomment-489316557)
> 沒在更新了呀....

那看下我主页的 sqlmap-wx, 上个月重新写的一版, 跨平台, win也能使用.
和sqlmap-gtk几乎一模一样.
只是运行的时候会打开一个终端(wxpython没有终端组件)
而sqlmap-gtk内嵌了一个终端.
