### ISSUE TITLE
english version?

### ISSUE THREAD

**Issue by azamet90** [needle-wang/sqlmap-gtk#3]
does it have english language?

**Comment by needle-wang** [comment]
no, english words will mess the GUI's layout.

**Comment by azamet90** [comment]
> no, english words will mess the GUI's layout.

i see... i will not download it but as i can see on the images this tool looking good

**Comment by needle-wang** [comment]
thank you

**Comment by needle-wang** [comment]
> 
> 
> > no, english words will mess the GUI's layout.
> 
> i see... i will not download it but as i can see on the images this tool looking good

thank you!

**Comment by abcsell** [comment]
I just need it. It's too much trouble to remember orders

**Comment by needle-wang** [comment]
> I just need it. It's too much trouble to remember orders

, which is the reason that i code the gui.

**Comment by needle-wang** [comment]
english is default language now.
