### ISSUE TITLE
结果输出那里无法复制粘贴

### ISSUE THREAD

**Issue by GlobeMasterX** [needle-wang/sqlmap-gtk#4]
如果把这个问题解决就好了，因为很多结果都需要复制粘贴的，比如说跑出来的MD5密码，等等很多都需要把结果复制

**Comment by needle-wang** [comment]
> 如果把这个问题解决就好了，因为很多结果都需要复制粘贴的，比如说跑出来的MD5密码，等等很多都需要把结果复制

选中即复制, 按下鼠标中键 或 按shift+insert可粘贴.

**Comment by needle-wang** [comment]
done at version 0.3.4.3
- 右键会弹出复制粘贴按钮
- 右键-c,v键, 助记符进行复制粘贴
- ctrl-shift-c, v键, 快捷键进行复制粘贴
